services:
  - type: web
    name: participatorysurvey
    runtime: python
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python platform_server.py
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: ADMIN_KEY
        generateValue: true
